### ISSUE TITLE
Final Week Before Milestone 3 :)

### ISSUE THREAD

**Issue by xiaorui-ui** [xiaorui-ui/WordleMadness#24]
Bugs to resolve:
- [x] Disable concurrent logging in of same account(eventListener, isLoggedIn) 
- [x] Add protection in the algo for "a, b, c, d,..." (error handling) 

Add ons:
- [x] Store decision tree for each user
- [x] Allow for different decision tree widths (should be simple)

Optional add-ons:
- Consider splitting the solve function into the actual solving and hashing separately to test for timing
- Store word lists in hashmap instead of list
- Solve with different shortlisting functions

Testing:
FE
    - Snapshot testing
    - Decision tree rendering behaviour
    - Inputting words
    - Solving simple lists
    - Input txt lists
    - Test everything when logged out
BE
I'm not sure lmao

User Testing
- [x] Ask some friends, best to finalize everything before ~Wednesday so that we can make final improvements
